spring:
  datasource:
    druid:
      initial-size: 0
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
         driver-class-name: com.mysql.cj.jdbc.Driver
         url: jdbc:mysql://120.27.130.210:3306/blog?useUnicode=true&characterEncoding=utf-8
         username: root
         password: 123456
         druid:
           initial-size: 10
           max-active: 30

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

logging:
  level:
    root: info
    com.tpp: debug
  file:
    name: log/blog-dev.log



